### ISSUE TITLE
-balance not works with Python 3.10.0

### ISSUE THREAD

**Issue by AngelTs** [jackjack-jj/pywallet#40]
>python pywallet.py --balance="aaa"
>AttributeError: module 'urllib' has no attribute 'urlopen'.

Is there a way to install urllib for Python 2.7 in Python3.10?
